language: c
dist: trusty
branches:
  only:
    - master

services: redis-server

# We don't need recursive submodule, so do it manually
git:
  submodules: false

addons:
  apt:
    update: true
    packages:
      - cmake
      - gcc
      - g++
      - make
      - libgc-dev
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - libncurses5-dev
      - curl

before_install:
  - git submodule update --init
  - curl https://raw.githubusercontent.com/ktakashi/scheme-env/master/bin/install.sh | bash
  - export PATH=$PATH:~/.scheme-env/bin

install:
  - scheme-env install sagittarius@0.9.4
  - scheme-env install chez@v9.5
#  - scheme-env install larceny@1.3

script:
  - ./run-test.sh
